SELECT * FROM [Contact]
SELECT * FROM [Address]
--SELECT * FROM [State]


BEGIN TRANSACTION

DELETE C FROM [Contact] AS C WHERE C.ID > 6
DELETE A FROM [Address] AS A WHERE A.ID > 7

COMMIT TRANSACTION
--ROLLBACK TRANSACTION